[package]
name = "terragrunt-ls"
version = "0.2.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
sha2 = "0.10.9"
zed_extension_api = "0.2.0"
zip = { version = "2.4.2", default-features = false, features = ["deflate"] }

[dev-dependencies]
tree-sitter = "0.25.3"
tree-sitter-hcl = "1.1.0"
