id = "terragrunt-ls-deadsen"
name = "deadsen Terragrunt"
version = "0.1.0"
schema_version = 1
authors = [
	"Arsen Yushchenko <goclever899@gmail.com>",
	"Tomasz Warczykowski <tomasz.warczykowski@silksh.pl>",
	"Terragrunt Language Server Contributors"
]
description = "Unofficial Terragrunt Language Server extension maintained by deadsen"
repository = "https://github.com/deadsen/terragrunt-ls"

[language_servers.terragrunt]
name = "Terragrunt LSP"
languages = ["Terragrunt"]
language_ids = { Terragrunt = "terragrunt" }

[grammars.hcl]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-hcl"
commit = "9e3ec9848f28d26845ba300fd73c740459b83e9b"
